# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-04 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20161204_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='location',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='country',
            field=models.CharField(default='Unknown', max_length=60),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='state',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='street',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
